Repository duckth/bdsa-project-newgit, pull requests merged in 2022-11, with the labels that each got.

#27 update with week three description
  README.md
  docs/project-description.md
Labels: documentation

#59 Feature/fork analysis endpoint
  NEWgIT.Core.Tests/Usings.cs
  NEWgIT.Core/ICommitFetcherService.cs
  NEWgIT.Core/Response.cs
  NEWgIT.Core/Services/CommitFetcherService.cs
  NEWgIT.Core/Services/ForkFetcherService.cs
  NEWgIT.Core/Services/ICommitFetcherService.cs
  NEWgIT.Core/Services/IForkFetcherService.cs
  NEWgIT.Infrastructure.Tests/Usings.cs
  NEWgIT.Infrastructure/AnalysisRepository.cs
  NEWgIT.Tests/Controllers/AnalysisControllerTests.cs
  NEWgIT/Controllers/AnalysisController.cs
  NEWgIT/NEWgIT.csproj
  NEWgIT/Program.cs
  NEWgIT/Usings.cs
Labels: enhancement

#64 Rest api test update
  NEWgIT.Tests/Controllers/AnalysisControllerTests.cs
  NEWgIT/Controllers/AnalysisController.cs
Labels: test

#65 add week 4 requirements
  docs/doc.md
  docs/project-description.md
Labels: documentation

#69 add week 5 Non-func/Func requirements
  docs/doc.md
Labels: documentation, requirement

#70 Implement repository tests
  NEWgIT.Infrastructure.Tests/AnalysisRepositoryTests.cs
Labels: test, requirement

#72 setup classes and packages
  docs/diagrams-code.md
  docs/diagrams.md
  images/activity_diagram.png
  images/package_diagram.png
Labels: documentation, requirement
